import React, { useState, useEffect } from "react";
import PostCard from "../components/ui/PostCard";
import { usePosts } from "../hooks/usePosts";
import "./Home.css";

// --- TYPES ---
interface GitHubEvent {
  id: string;
  type: string;
  created_at: string;
  repo: { name: string };
  payload: {
    ref?: string;
    commits?: Array<{
      sha: string;
      message: string;
    }>;
  };
}

// The structure of the JSON file generated by your script
interface StaticDataResponse {
  lastUpdated: number;
  events: GitHubEvent[];
}

const Home: React.FC = () => {
  const { getAllPosts } = usePosts();
  const latestPosts = getAllPosts().slice(0, 3);

  // UI State
  const [time, setTime] = useState(new Date());

  // Data State
  const [activityMap, setActivityMap] = useState<number[]>(Array(30).fill(0));
  const [ghStatus, setGhStatus] = useState<"LOADING" | "ONLINE" | "OFFLINE">(
    "LOADING",
  );
  const [dataTimestamp, setDataTimestamp] = useState<number | null>(null);

  // --- LIVE CLOCK ---
  useEffect(() => {
    const timer = setInterval(() => setTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  // --- HELPER: PROCESS HEATMAP ONLY ---
  const processHeatmap = (events: GitHubEvent[]) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0); // Normalize to midnight

    const thirtyDaysAgo = new Date(today);
    thirtyDaysAgo.setDate(today.getDate() - 30);

    // Filter relevant events
    const pushEvents = events.filter((e) => {
      return e.type === "PushEvent" && new Date(e.created_at) >= thirtyDaysAgo;
    });

    // Calculate Heatmap Density (Last 30 Days)
    const dailyCounts = Array(30).fill(0);

    pushEvents.forEach((e) => {
      const eventDate = new Date(e.created_at);
      eventDate.setHours(0, 0, 0, 0);

      // Calculate day difference
      const diffTime = today.getTime() - eventDate.getTime();
      const dayDiff = Math.floor(diffTime / (1000 * 3600 * 24));

      // Map to array index (29 is Today, 0 is 30 days ago)
      if (dayDiff >= 0 && dayDiff < 30) {
        // If commits array exists, sum them. If not, count the event as 1.
        const count = e.payload.commits ? e.payload.commits.length : 1;
        dailyCounts[29 - dayDiff] += count;
      }
    });

    return dailyCounts;
  };

  // --- DATA FETCHING (FROM STATIC JSON) ---
  useEffect(() => {
    let isMounted = true;

    const fetchStaticData = async () => {
      try {
        const response = await fetch(`/github-data.json?t=${Date.now()}`);

        if (!response.ok) {
          throw new Error("Local data not found (404)");
        }

        const data: StaticDataResponse | GitHubEvent[] = await response.json();

        let events: GitHubEvent[] = [];
        let timestamp = Date.now();

        if (Array.isArray(data)) {
          events = data;
        } else {
          events = data.events;
          timestamp = data.lastUpdated;
        }

        if (isMounted) {
          const dailyCounts = processHeatmap(events);
          setActivityMap(dailyCounts);
          setDataTimestamp(timestamp);
          setGhStatus("ONLINE");
        }
      } catch (error) {
        console.error("Failed to load static GitHub data:", error);
        if (isMounted) setGhStatus("OFFLINE");
      }
    };

    fetchStaticData();

    return () => {
      isMounted = false;
    };
  }, []);

  // Helper for Heatmap Opacity
  const getIntensity = (count: number) => {
    if (count === 0) return 0.1;
    if (count <= 2) return 0.4;
    if (count <= 5) return 0.7;
    return 1;
  };

  return (
    <div className="home-container fade-in">
      {/* --- HERO SECTION --- */}
      <header className="hero-section">
        <div className="hero-main">
          <h1 className="hero-title">
            LALIT<span className="accent">_</span>MADAN
          </h1>
          <p className="hero-subtitle">
            Engineering Reality. Architecting Intelligence.
          </p>
        </div>

        <div className="hero-telemetry">
          <div className="tele-row">
            <span className="t-label">LOC</span>
            <span className="t-val">IND_REGION</span>
          </div>
          <div className="tele-row">
            <span className="t-label">TICK</span>
            <span className="t-val numeric">
              {time.toLocaleTimeString("en-GB", { hour12: false })}
            </span>
          </div>
          <div className="tele-row">
            <span className="t-label">NET</span>
            <span
              className={`t-val ${ghStatus === "ONLINE" ? "active" : "offline"}`}
            >
              {ghStatus}
            </span>
          </div>
        </div>
      </header>

      <main className="sys-grid">
        {/* [LEFT COL] CONTEXT */}
        <aside className="grid-sidebar">
          <div className="sys-module">
            <div className="mod-header">/// SYSTEM_DESCRIPTION</div>
            <p className="mod-text">
              Full-stack engineer building digital systems that bridge logic and
              creativity.
            </p>
            <div className="status-indicator">
              <span className="status-dot pulse"></span>
              <span>FOCUS: Agentic Workflows</span>
            </div>
          </div>

          <div className="sys-module">
            <div className="mod-header">/// RUNTIME_ENV</div>
            <div className="tag-cloud">
              {["React", "Javascript", "Python", "Docker"].map((t) => (
                <span key={t} className="sys-tag">
                  {t}
                </span>
              ))}
            </div>
          </div>

          <div className="sys-module">
            <div className="mod-header">/// COMM_PORTS</div>
            <div className="comm-grid">
              <a
                href="https://github.com/madanlalit/"
                className="comm-link"
                target="_blank"
                rel="noreferrer"
              >
                GITHUB
              </a>
              <a
                href="https://linkedin.com/in/madanlalit/"
                className="comm-link"
                target="_blank"
                rel="noreferrer"
              >
                LINKEDIN
              </a>
              <a
                href="https://x.com/lalitmadan/"
                className="comm-link"
                target="_blank"
                rel="noreferrer"
              >
                X / TW
              </a>
            </div>
          </div>
        </aside>

        {/* [RIGHT COL] DATA STREAMS */}
        <section className="grid-main">
          {/* 5. GITHUB HEATMAP MODULE */}
          <div className="sys-module activity-wrapper">
            <div className="mod-header">
              <span>/// COMMIT_HISTORY</span>

              {/* STATUS META DATA */}
              {ghStatus === "ONLINE" && dataTimestamp && (
                <span
                  className="mod-meta"
                  style={{ color: "var(--text-secondary)" }}
                >
                  DATA_SYNCED:{" "}
                  {new Date(dataTimestamp).toLocaleTimeString([], {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </span>
              )}
              {ghStatus === "OFFLINE" && (
                <span className="mod-meta error-text">DATA_Unavailable</span>
              )}
              {ghStatus === "LOADING" && (
                <span className="mod-meta">INITIALIZING...</span>
              )}
            </div>

            {/* Visual Heatmap */}
            <div className="heatmap-strip">
              {activityMap.map((count, i) => (
                <div
                  key={i}
                  className="heat-bit"
                  style={{
                    opacity: getIntensity(count),
                    backgroundColor:
                      count > 0 ? "var(--accent)" : "var(--text-tertiary)",
                  }}
                  title={`${count} commits (${30 - i - 1} days ago)`}
                />
              ))}
            </div>
            {/* Log List removed here */}
          </div>

          {/* 6. LATEST BLOG POSTS */}
          <div className="sys-module">
            <div className="mod-header">
              <span>/// SYSTEM_[B]LOGS</span>
              <span className="mod-meta">[{latestPosts.length}]</span>
            </div>

            <div className="logs-timeline">
              {latestPosts.map((post, index) => (
                <div key={post.id} className="timeline-entry">
                  <div className="timeline-marker">
                    <div className="t-dot"></div>
                    <div className="t-line"></div>
                  </div>
                  <div className="timeline-content">
                    <div className="clean-card">
                      <PostCard post={post} index={index} />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="sys-footer">
        <div className="f-left">
          <span className="f-item">SYS_ID: 0x1A4</span>
          <span className="f-item">REACT_DOM</span>
        </div>
        <div className="f-right">
          <a href="/rss">RSS</a>
          <span className="sep">/</span>
          <a href="/sitemap">MAP</a>
        </div>
      </footer>
    </div>
  );
};

export default Home;
